import Foundation
import UniformTypeIdentifiers

// MARK: - File Source

/// Where a locally-stored file originated from.
enum FileSource: String, Codable {
    /// Picked by the user via PhotosPicker/.fileImporter and attached to a prompt.
    case userUpload
    /// Returned/generated by the LLM as part of a response.
    case llmOutput
}

// MARK: - Stored File Metadata

struct StoredFileMetadata: Identifiable, Codable, Equatable {
    let id: String
    let conversationId: String
    let filename: String
    let mimeType: String
    let byteSize: Int
    let createdAt: Date
    let source: FileSource
    /// The backend URL this file was uploaded to or downloaded from, if any.
    /// Nil for a user attachment that hasn't finished uploading yet.
    let remoteURL: String?

    init(
        id: String = UUID().uuidString,
        conversationId: String,
        filename: String,
        mimeType: String,
        byteSize: Int,
        createdAt: Date = Date(),
        source: FileSource,
        remoteURL: String? = nil
    ) {
        self.id = id
        self.conversationId = conversationId
        self.filename = filename
        self.mimeType = mimeType
        self.byteSize = byteSize
        self.createdAt = createdAt
        self.source = source
        self.remoteURL = remoteURL
    }

    var utType: UTType {
        UTType(mimeType: mimeType) ?? UTType(filenameExtension: (filename as NSString).pathExtension) ?? .data
    }

    var formattedSize: String {
        let bytes = Double(byteSize)
        if bytes < 1024 { return "\(byteSize) B" }
        if bytes < 1_048_576 { return String(format: "%.1f KB", bytes / 1024) }
        return String(format: "%.1f MB", bytes / 1_048_576)
    }
}

// MARK: - File Store Protocol

/// Persistence abstraction for user-attached and LLM-generated files.
///
/// `LocalFileStore` is the only implementation today (native clients keep
/// files on-device, not in a remote object store). The protocol is shaped so
/// a future implementation (e.g. one backed by the same MinIO/S3 store the
/// web app uses) could conform without call sites changing.
protocol FileStore {
    /// Persists `data` under `conversationId` and returns its metadata.
    @discardableResult
    func save(
        data: Data,
        filename: String,
        mimeType: String,
        conversationId: String,
        source: FileSource,
        remoteURL: String?
    ) async throws -> StoredFileMetadata

    /// Loads the bytes for a previously-saved file.
    func load(_ metadata: StoredFileMetadata) async throws -> Data

    /// Lists all files stored for a conversation, oldest first.
    func list(conversationId: String) async throws -> [StoredFileMetadata]

    /// Removes a single file.
    func delete(_ metadata: StoredFileMetadata) async throws

    /// Removes every file stored for a conversation (e.g. when it's deleted).
    func deleteAll(conversationId: String) async throws

    /// A file:// URL suitable for QuickLook/ShareLink. Implementations that
    /// don't keep bytes on local disk would need to materialize a temp file.
    func fileURL(for metadata: StoredFileMetadata) async throws -> URL

    /// Re-saves metadata with an updated remote reference (e.g. once a
    /// pending upload completes and a backend URL becomes available).
    @discardableResult
    func updateRemoteURL(_ remoteURL: String, for metadata: StoredFileMetadata) async throws -> StoredFileMetadata
}

enum FileStoreError: LocalizedError {
    case notFound
    case ioError(String)

    var errorDescription: String? {
        switch self {
        case .notFound: return "File not found."
        case .ioError(let message): return "File storage error: \(message)"
        }
    }
}
